# Auto-generated by compose2nix.
{
  pkgs,
  lib,
  config,
  ...
}: {
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll =
      if !config.networking.nftables.enable
      then "podman+"
      else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [53];
  };

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."filestash" = {
    image = "machines/filestash:latest";
    environment = {
      "APPLICATION_URL" = "";
      "CANARY" = "true";
      "OFFICE_FILESTASH_URL" = "http://app:8334";
      "OFFICE_REWRITE_URL" = "http://127.0.0.1:9980";
      "OFFICE_URL" = "http://wopi_server:9980";
    };
    volumes = [
      "filestash_filestash:/app/data/state:rw"
    ];
    ports = [
      "8334:8334/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=app"
      "--network=filestash_default"
    ];
  };
  systemd.services."podman-filestash" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-filestash_default.service"
      "podman-volume-filestash_filestash.service"
    ];
    requires = [
      "podman-network-filestash_default.service"
      "podman-volume-filestash_filestash.service"
    ];
    partOf = [
      "podman-compose-filestash-root.target"
    ];
    wantedBy = [
      "podman-compose-filestash-root.target"
    ];
  };
  virtualisation.oci-containers.containers."filestash_wopi" = {
    image = "collabora/code:24.04.10.2.1";
    environment = {
      "aliasgroup1" = "\"https://.*:443\"";
      "extra_params" = "--o:ssl.enable=false";
    };
    ports = [
      "9980:9980/tcp"
    ];
    cmd = ["/bin/bash" "-c" "curl -o /usr/share/coolwsd/browser/dist/branding-desktop.css https://gist.githubusercontent.com/mickael-kerjean/bc1f57cd312cf04731d30185cc4e7ba2/raw/d706dcdf23c21441e5af289d871b33defc2770ea/destop.css
  /bin/su -s /bin/bash -c '/start-collabora-online.sh' cool
  "];
    user = "root";
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wopi_server"
      "--network=filestash_default"
    ];
  };
  systemd.services."podman-filestash_wopi" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-filestash_default.service"
    ];
    requires = [
      "podman-network-filestash_default.service"
    ];
    partOf = [
      "podman-compose-filestash-root.target"
    ];
    wantedBy = [
      "podman-compose-filestash-root.target"
    ];
  };

  # Networks
  systemd.services."podman-network-filestash_default" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f filestash_default";
    };
    script = ''
      podman network inspect filestash_default || podman network create filestash_default
    '';
    partOf = ["podman-compose-filestash-root.target"];
    wantedBy = ["podman-compose-filestash-root.target"];
  };

  # Volumes
  systemd.services."podman-volume-filestash_filestash" = {
    path = [pkgs.podman];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      podman volume inspect filestash_filestash || podman volume create filestash_filestash
    '';
    partOf = ["podman-compose-filestash-root.target"];
    wantedBy = ["podman-compose-filestash-root.target"];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-filestash-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = ["multi-user.target"];
  };
}
